models = {
    # Cars196
    "cars196 arcface": "<PATH TO MODEL>",
    "cars196 arcface bgaugment": "<PATH TO MODEL>",
    "cars196 contrastive": "<PATH TO MODEL>",
    "cars196 contrastive bgaugment": "<PATH TO MODEL>",
    "cars196 multi similarity": "<PATH TO MODEL>",
    "cars196 multi similarity bgaugment": "<PATH TO MODEL>",
    "cars196 normalized softmax": "<PATH TO MODEL>",
    "cars196 normalized softmax bgaugment": "<PATH TO MODEL>",
    "cars196 triplet": "<PATH TO MODEL>",
    "cars196 triplet bgaugment": "<PATH TO MODEL>",
    # CUB200
    "cub200 arcface": "<PATH TO MODEL>",
    "cub200 arcface bgaugment": "<PATH TO MODEL>",
    "cub200 contrastive": "<PATH TO MODEL>",
    "cub200 contrastive bgaugment": "<PATH TO MODEL>",
    "cub200 multi similarity": "<PATH TO MODEL>",
    "cub200 multi similarity bgaugment": "<PATH TO MODEL>",
    "cub200 normalized softmax": "<PATH TO MODEL>",
    "cub200 normalized softmax bgaugment": "<PATH TO MODEL>",
    "cub200 triplet": "<PATH TO MODEL>",
    "cub200 triplet bgaugment": "<PATH TO MODEL>",
    # SOP
    "sop arcface": "<PATH TO MODEL>",
    "sop arcface bgaugment": "<PATH TO MODEL>",
    "sop contrastive": "<PATH TO MODEL>",
    "sop contrastive bgaugment": "<PATH TO MODEL>",
    "sop multi similarity": "<PATH TO MODEL>",
    "sop multi similarity bgaugment": "<PATH TO MODEL>",
    "sop normalized softmax": "<PATH TO MODEL>",
    "sop normalized softmax bgaugment": "<PATH TO MODEL>",
    "sop triplet": "<PATH TO MODEL>",
    "sop triplet bgaugment": "<PATH TO MODEL>",
}