_target_: src.datamodules.stanford_online_products.SOPDataModule

root: ${data_dir}
batch_size: 32
num_workers: 4
train_transform:
  _target_: src.utils.transforms.TrainTransform
val_transform:
  _target_: src.utils.transforms.ValTransform
# Use 4 for ranking based losses, 1 for classification losses
m_per_class: 4